language: go
dist: xenial
sudo: true
services:
  - docker
matrix:
  allow_failures:
    - go: master
  include:
    - os: linux
      go: 1.13.x
      cache:
        directories:
          - "/home/travis/.cache/go-build"
    - os: linux
      go: master
    - os: windows
      go: 1.13.x
    - os: osx
      go: 1.13.x
      cache:
        directories:
          - "/Users/travis/Library/Caches/go-build"
before_install:
  - go get -u github.com/client9/misspell/cmd/misspell
  - go get -u golang.org/x/lint/golint
  - go get github.com/fzipp/gocyclo
  - go get -u honnef.co/go/tools/cmd/staticcheck
  - go get golang.org/x/tools/cmd/cover
before_script:
  - GOFILES=$(find . -type f -name '*.go' | grep -v vendor | grep -v client)
script:
  # Just check gofmt on linux, it's the fastest builder
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test -z $(gofmt -s -l $GOFILES); fi
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
  - misspell -error -locale US $GOFILES
  - gocyclo -over 20 $GOFILES
  - golint -set_exit_status $GOFILES
  - staticcheck *.go
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y mingw; export PATH=/c/tools/mingw64/bin:"$PATH";fi
after_success:
  - bash <(curl -s https://codecov.io/bash) -X fix
  - make
  - make docker
